[package]

name = "sl"
version = "0.1.0"
authors = [ "florian.gilcher@asquera.de" ]

[[bin]]

name = "sl"

[lib]

name = "sl"

[dependencies]

getopts = "0.2.14"
ctrlc = "*"

[dependencies.ncurses]

git = "https://github.com/jeaye/ncurses-rs.git"
